nameOverride: ENC[AES256_GCM,data:CAgds/di,iv:Yey2aGWk463AkWJJQW4Kw2/vve4McmGo/EsgZ4f/TIc=,tag:z+zi6pQ9pcagSNS8S3Jykw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-05T10:25:38Z"
    mac: ENC[AES256_GCM,data:NqqaxNLkOvWCBTkRLwxNisBejjL3LvLJPNnWNgejItU3kwPRx8j5LFDBibw8drvsxXfy2meScyIx0diMmntShHhNf3SSXhdbIgIkhKa3fafprPthmLdQiN+jdbNvJglO1z72jN3ajCz1+SGScVrdbEFGBq6/Nyumw2RR1jPla9M=,iv:mjUAxrH14FCqSPa6Wj8BIA8o21lv2U3oeY78MjgoOCg=,tag:Ebb+lqnSXieBt6aPaJvIEw==,type:str]
    pgp:
        - created_at: "2024-03-05T10:25:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2GEZyMZeZ8TAQ/+PV2RKE69QzUyPBdcZB4JoJN+n1PU6hGGGIcxXzhWLtBz
            mroVXN7GAfQeQUbUP2DuK41G/1dS8zNIe/mJurrjKOMDS0Xc80Z51A6e7dygfRQ5
            /DZPhkEEv0DHS0BcFxkVl+f0olwypRyEd1wSMFD/r/xN9eSOnRUW+//Tu5QC9f1H
            sHU9iRAsB3cBP1u7H3RzDUwK3eS0Jp0ty5s/WYZ0MhbH9obDOue/P006R1cuwDF+
            amzo/A4LAPTTD/jPh8M2WQPhqcHHz/jBlEIhdSMJZArJs/rrXMPk+aBGSTU+QIBk
            qtNalJj2Davxa0Kx4dco8Ps2+ISgUGNo33D8dI4P8HqzN4Xwaz+f+6qbyYeV1v72
            Pne01giALGGK/UZd2nWRntz1C6sS/G7fS9kk6Fw7BYF9EpbpG/kS86M6myKc/z2D
            yDaTXnpT+Hp1nZ67B71ubE39/dDmA52kTUa5COUvZp87s7ondCEX7/z3ryoE0L0T
            cBBVM17MMw7IQBKkduI06PkE+b/qYuHqrkojtnyjNiLYuh/V2HtgImcYPtDFQW/s
            hDCVo6Xhy7w0GNnw4jk083OdXXEO4sKp27EbrpCdV3inBkWmrL+FaXKMvf44hD77
            PiTQlBQI/mnzn8DhG7RpfqYUUcG3Y1GwpG/VA3svvtYqXAca7NyjkNLvNQ7lVaLU
            aAEJAhBTKXOM3ImxOA/dqi8xKMgH1+K2N94hbR9+XfkSpL7WjWvwi3JEuifYNa+6
            2S8FdnQkiDN6wVXj1dmkszSO5bUw6G3OaQrEOqfMFwlH7wViAwAJ04H4pVmPfJlG
            kFYB7wX1+OR1
            =pNb3
            -----END PGP MESSAGE-----
          fp: C7299E0D6937E316A348B966D154F6DE302E1AE8
    unencrypted_suffix: _unencrypted
    version: 3.8.1
